language: java
jdk:
- oraclejdk8
env:
  global:
  - secure: cID0zXRLjdJ0NEBWzkjTLLW5eJ/6YIbCoHEqXz+uvDBTrBGC+LBJjew7TNc4wamBEwMtOqRPSNii0FXkRyhVyC3vRxS5e2+tsDv6XKHC2yRFfjZg1pqgwHcp2lh3K7Tr24M+pnKH2CrpByL0mWzu8pt3Et5AJd275bw6BkFAEryRiALC5Rlb8D5K3pJ/30uRIuxM7P66cEvmpBDjLuen27FRyxwiR1M9gGHRrDfNicmh44JUTzB77C0iCL2LBeuyqnyDv6XT8w2FFoTocX5bvWpFYvxXjJRiLDq6P9AJrWLO4BHkPclZunyS/LQWkSK+ojUqQpzWicXvEhwcLFpNMEWWpmY+ioY65c+AZpHP29mpC2eVYQOPyZTAs26XFktE82gp2QdJ2wir+CjfiZnFNP61p6f9qUHb2GvprzgDAiLZmsdyrn2emZT8duazQkucPI4fpxMWLWVKDSSGilASGeOE4REmACIqnepE0AZP5sfreQDI2C2mhrDtR7OpFUHLF2+OvftiMj/efYwIwSAFs01s/+XZm9+Y28Vd4GPbU8125MPf30xN4ys6x75pyHkxcmGibkHMTe7UXcmYsmV6bbterynzyfECvIfXV7B6oWUleYqdzRLSoyHUJUrc5vJevj3rANET9vv+HrOA+eFpkJPXVJPWIntJO9SEgbWOsUY=
  - secure: pGywYMtrdEHEtUbbul2hHOCiEy//WAveX5mx9d2JLva5CLlyWqBL/7IFchsyy7cjEqAjvq4zwcPHLMFanSi/SA3T+Ur5jzhrWc/3n7kzaBVNhiph+Sjut1CE1LnjvlQ3IONvqInYjtZgv5Lvs0Yxtf8mdiPcx3YNhDcs5emvjyI1XLYGRJ20hsG3vC/qSeIdtBeXo5a7vuRRfBNJMOnlOCd5j2SGEI92K2Hh3JIAqNax9NU59vRzA/sWb3Dm13wny8HKYCGQp120mpSrK8y3VFLbmMBfEtWz5Nbqaz12As8r37MOkKeXvLRXCahX272KlwTtbyRqmB/5fS0vvKcYvQ7C59m1BtjCLV0PEFUp0Rk/KkHUoJRKuVMfh2aIJgcON6EdOB7C9z4FGI1YB2yv1pjEWdVLU6HA8WMNGb8+SXfNAUMjqlyyPkC9wSJsqOY45sONlA+VtRebU84K1p9GbSBKAcuxKb50rpR+kgF0rn/MMr7FBgp9MDZ9v/LucoCU0l/VrM6FGkYrsnQOdAh5Kz4BbLbHSRavLpcQ5su8QJzywmJAJ6Qc0oIpYqLYEDcQktwBLpCJALmhCekI+yCWych6E/T5fgelQksqGMtxp03asA7AV1pjFuvQEJWEAUof1szTx3co5XCvfbXQNfl7Lo/UvxamfbPmSOCTmatvdAU=
script:
  - ./gradlew check
  - ./gradlew codeCoverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./gradlew uploadArchives -PnexusUsername="${SONATYPE_USER}" -PnexusPassword="${SONATYPE_PASS}"
